
== 理解领域、子域、限界上下文

领域（Domain）既可以表示整个业务系统，也可以表示其中的某个核心域或者支撑子域。
几乎所有软件的领域都包含多个子域，这和软件系统本身的复杂性没有太大关系。

限界上下文（Bounded Context）是语义和语境的边界。边界内的每个代表软件模型的组件都有着特定的含义并处理特定的事务。
通用语言（Ubiquitous Language）是团队在限界上下文中发展了一种语言用于表达其边界内的软件模型，这一语言由在该限界上下文中开发软件模型的每个成员所使用。
领域模型把通用语言表达成软件模型。
限界上下文是一个显示边界，领域模型便存在于边界之内。
限界上下文是显示的并充满语义的。
不要试图创建一个大而全的软件模型（如每种概念在全局范围之内只有一种定义）。
限界上下文不规定只能创建一种类型的项目工件。它不是一个独立的组件，文档或者简图。

=== 问题空间（Problem Space）和解决方案空间（Solution Space）
问题空间是在给定项目的约束条件下进行高级战略分析与设计各个步骤的地方。
解决方案空间是真正实施解决方案的地方，这些解决方案在问题空间讨论中被识别为核心域（Core-domain）
核心域是限界上下文被当作组织的关键战略举措进行开发时。

在问题空间中，我们思考的是待解决的战略性业务挑战，而在解决方案空间中，我们思考如何实现软件以解决这些业务挑战。
问题空间是需要开发并划分出核心域的领域的一部分，解决方案空间是一个或多个限界上下文，一组特定软件模型。

==== 如何对问题空间和解决方案空间评估
. 战略核心域的名称是什么，愿景是什么？
. 应该考虑哪些概念作为战略核心域的一部分？
. 有哪些必要的支撑子域和通用子域？
. 谁应该在每个领域区域进行工作？
. 能召集出一个正确的团队吗？


== 核心域、支撑子域、通用子域
核心域（Core Domain）：整个业务领域的一部分，也是业务成功的主要促成因素。从战略层面上讲，企业应该在核心域上胜人一筹。应该给予核心域最高的优先级、最资深的领域专家和最优秀的开发团队。在实施ddd过程中，主要关注核心域。
支撑子域（Supporting Subdomain）：限界上下文对应着业务的某些重要方面，但不是核心，通常通过创建或者购买这个限界上下文来支撑业务，创建支撑子域的原因在于它们专注于业务的某个方面
通用子域（Generic Subdomain）：一个子域被用于整个业务系统，那么这个子域便是通用子域。
实线：表示不同子域之间的集成关系，表明不同的模型是需要协同工作的。
实现界分限界上下文，虚线隔开不同的子域，不同子域和限界上下文之间的直线表示集成关系



== 白板时间（Whiteboard Time）

=== 绘制表示项目的领域、子域、限界上下文的框图
. *一栏列出日常工作中的子域，一栏列出限界上下文*。可能存在限界上下文和子域相交的地方
. 以“An abstract business Domain that includes subdomains and bounded contexts” 为模板，填入自己的软件项目中的子域、限界上下文和集成关系
. 优化上一步所形成的图，画出能表示你的领域、子域和限界上下文的框图。

=== 标识核心域、支撑子域以及通用子域
. 标识核心域
. 标识支撑子域、通用子域
. 不时地向领域专家提问纠正

=== 思考问题空间是什么
问题空间是战略核心域和支撑它的子域的组合。

=== 在你的解决方案空间里，限界上下文是什么