
战略设计的重要性
. 学习领域、子域和限界上下文
. 学习问题空间和解决方案空间
. 学到了如何利用限界上下文分离模型
. 学到了如何正确处理限界上下文的大侠，如何构建可以部署的限界上下文

== 理解领域、子域、限界上下文

领域（Domain）既可以表示整个业务系统，也可以表示其中的某个核心域或者支撑子域。
几乎所有软件的领域都包含多个子域，这和软件系统本身的复杂性没有太大关系。

限界上下文（Bounded Context）是语义和语境的边界。边界内的每个代表软件模型的组件都有着特定的含义并处理特定的事务。
通用语言（Ubiquitous Language）是团队在限界上下文中发展了一种语言用于表达其边界内的软件模型，这一语言由在该限界上下文中开发软件模型的每个成员所使用。
领域模型把通用语言表达成软件模型。
限界上下文是一个显示边界，领域模型便存在于边界之内。
限界上下文是显示的并充满语义的。
不要试图创建一个大而全的软件模型（如每种概念在全局范围之内只有一种定义）。
限界上下文不规定创建一种类型的项目工件。它不是一个独立的组件，文档或者示意图。
模型是限界上下文的主要公民，除此之外，它通常把一个系统、应用程序或者一个业务服务划开，有时包含的内容很少，比如一个通用子域可以只包含领域模型。

一个限界上下文可能包括的内容：

. 当领域模型驱动数据库schema的设计，数据库schema应在该模型所处的上下文边界之内
. 当UserInterface被用于渲染模型并且驱动模型的行为设计时，User Interface应在该模型所在的上下文边界之内
. 使用Open Host Service（REST资源）或者SOAP或消息服务端点与模型交互，这些面向服务的组件都应该位于上下文边界之内
. 应用服务也是位于上下文边界之内的

导致创建大小不正确的限界上下文的因素
. 错误地采用架构来指导设计开发，而不是通用语言
. 根据开发任务的分配来拆分限界上下文
. 没有考虑领域专家采用语言划分上下文边界的方式

=== 问题空间（Problem Space）和解决方案空间（Solution Space）
问题空间是在给定项目的约束条件下进行高级战略分析与设计各个步骤的地方。
解决方案空间是真正实施解决方案的地方，这些解决方案在问题空间讨论中被识别为核心域（Core-domain）
核心域是限界上下文被当作组织的关键战略举措进行开发时。

在问题空间中，我们思考的是待解决的战略性业务挑战，而在解决方案空间中，我们思考如何实现软件以解决这些业务挑战。
问题空间是需要开发并划分出核心域的领域的一部分，解决方案空间是一个或多个限界上下文，一组特定软件模型。

==== 如何对问题空间和解决方案空间评估
. 战略核心域的名称是什么，愿景是什么？
. 应该考虑哪些概念作为战略核心域的一部分？
. 有哪些必要的支撑子域和通用子域？
. 谁应该在每个领域区域进行工作？
. 能召集出一个正确的团队吗？


== 核心域、支撑子域、通用子域
核心域（Core Domain）：整个业务领域的一部分，也是业务成功的主要促成因素。从战略层面上讲，企业应该在核心域上胜人一筹。应该给予核心域最高的优先级、最资深的领域专家和最优秀的开发团队。在实施ddd过程中，主要关注核心域。
支撑子域（Supporting Subdomain）：限界上下文对应着业务的某些重要方面，但不是核心，通常通过创建或者购买这个限界上下文来支撑业务，创建支撑子域的原因在于它们专注于业务的某个方面
通用子域（Generic Subdomain）：一个子域被用于整个业务系统，那么这个子域便是通用子域。
实线：表示不同子域之间的集成关系，表明不同的模型是需要协同工作的。
实现界分限界上下文，虚线隔开不同的子域，不同子域和限界上下文之间的直线表示集成关系



== 白板时间（Whiteboard Time）

=== 绘制表示项目的领域、子域、限界上下文的框图
. *一栏列出日常工作中的子域，一栏列出限界上下文*。可能存在限界上下文和子域相交的地方
. 以“An abstract business Domain that includes subdomains and bounded contexts” 为模板，填入自己的软件项目中的子域、限界上下文和集成关系
. 优化上一步所形成的图，画出能表示你的领域、子域和限界上下文的框图。

=== 标识核心域、支撑子域以及通用子域
. 标识核心域
. 标识支撑子域、通用子域
. 不时地向领域专家提问纠正

=== 在项目中考虑问题空间
问题空间是战略核心域和支撑它的子域的组合。

=== 在解决方案空间里明确限界上下文

=== 标识限界上下文中区别微小的概念
* 在多种限界上下文中，识别出微小区别的概念
* 查明这些概念是否做出正确地分离，或者在两边做简单的代码复制开发。

=== 标识边界内的非领域模型组件
* A User Interface 或 A set of Application services
* database schema 或 other persistence store
* 模块、聚合、领域事件或领域服务等领域模型中的基础部件

=== 绘制限界上下文
* 使用通用语言进行考虑，并为你的模型绘制一个限界上下文
* 填上主要领域的概念，发现遗漏的概念和不应该出现的概念，并解决它们